### PR TITLE
Create a cron job to disassociate training roles from groups after the training ends

### PR DESCRIPTION
**Pull request by natefoo**
For the new feature added by @hexylena in usegalaxy-eu/tiaas2#21

Also fix a bug with the `run_once` stuff I previously added (not sure how I didn't have problems with it before but ok).

### CODE REVIEW

**Review by bgruening — APPROVED** [review]
Makes sense to me. Thanks.

**Review by hexylena — APPROVED** [review]

**Comment by hexylena** [comment]
This looks good and further convinces me we need to be doing systemd timers for this sort of thing, the logging would be taken care of and a lot easier to deal with.

**Comment by gmauro** [comment]
Do you know from which version of Ansible is available the truthy test?
I am having troubles with 2.9.19, and moreover they changed completely the name of the pip packages

**Comment by gmauro** [comment]
got it. 2.10
https://github.com/ansible/ansible/pull/62602/files

**Pull request merged**
